name: '[CD] Push docker image'

on:
  workflow_dispatch: 
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: git checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Installation de Java
        uses: actions/setup-java@v4
        with:
          java-version: 25
          distribution: temurin

      - name: Cache Maven
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: 'Compilation en .jar'
        run: mvn clean package -DskipTests

      - name: 'Copie du projet vers build'
        run: |
          cp 'target/ApiWebTool.jar' 'build/docker/projet.jar'

      - name: 'Récupération du dernier tag'
        id: version
        run: |
          LAST_TAG=$(git describe --tags --abbrev=0)
          VERSION=${LAST_TAG#v}
          IFS='.' read -r MAJOR MINOR PATCH <<< "$VERSION"
          PATCH=$((PATCH + 1))
          NEW_TAG="v$MAJOR.$MINOR.$PATCH"

          echo "NEW_TAG=$NEW_TAG" >> $GITHUB_ENV

      - name: Create tag
        run: |
          git tag $NEW_TAG
          git push origin $NEW_TAG

      - name: Build image docker Latest
        run: docker build ./build/docker --file ./build/docker/Dockerfile --tag ${{ secrets.DOCKER_USERNAME }}/apiwebtool:latest

      - name: Build image docker Tag
        run: docker build ./build/docker --file ./build/docker/Dockerfile --tag ${{ secrets.DOCKER_USERNAME }}/apiwebtool:$NEW_TAG
        

      - name: Login into docker account
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker Image Latest
        run: docker push ${{ secrets.DOCKER_USERNAME }}/apiwebtool:latest

      - name: Push Docker Image Tag
        run: docker push ${{ secrets.DOCKER_USERNAME }}/apiwebtool:$NEW_TAG
          
