name: '[CI] Tests Unitaires'

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: git checkout
        uses: actions/checkout@v4
        
      - name: Installation de Java
        uses: action/setup-java@v3
        with:
          java-version: 25
          distribution: temurin
          
      - name: Mise en cache des dépendances Maven
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Run JUnit5 tests
        run: mvn clean test

      - name: Upload des resultats de tests
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: junit-reports
          path: target/surefire-reports
  
